<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\GamePath.props" Condition="Exists('..\GamePath.props')" />
  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
    <LangVersion>preview</LangVersion>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="$(WrathInstallDir)\Wrath_Data\Managed\UnityModManager\UnityModManager.dll" Private="false" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all" />
  </ItemGroup>
</Project>
